dev_trw_lb_find_longboarder_show:
    path:     /{id}/show
    defaults: { _controller: "DevTRWLbFindBundle:Longboarder:show" }

dev_trw_lb_find_longboarder_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevTRWLbFindBundle:Longboarder:edit" }

dev_trw_lb_find_longboarder_update:
    path:     /{id}/update
    defaults: { _controller: "DevTRWLbFindBundle:Longboarder:update" }
    requirements: { _method: post|put }

dev_trw_lb_find_longboarder_delete:
    path:     /{id}/delete
    defaults: { _controller: "DevTRWLbFindBundle:Longboarder:delete" }
    requirements: { _method: post|delete }

dev_trw_lb_find_longboarder_new:
    path:     /new
    defaults: { _controller: "DevTRWLbFindBundle:Longboarder:new" }

dev_trw_lb_find_longboarder_create:
    path:     /create
    defaults: { _controller: "DevTRWLbFindBundle:Longboarder:create" }
    requirements: { _method: post }

dev_trw_lb_find_longboarder:
    path:     /
    defaults: { _controller: "DevTRWLbFindBundle:Longboarder:index" }

