dev_trb_lb_find_api:
    resource: @DevTRWLbFindBundle/Resources/config/routing_api.yml
    prefix: /api

dev_trw_lb_find_longboarder:
    resource: "@DevTRWLbFindBundle/Resources/config/routing/longboarder.yml"
    prefix: /longboarder

dev_trw_lb_find_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DevTRWLbFindBundle:Default:index }

